/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "GPIO_DRIVER/gpio.h"
#include "EXTI_DRIVER/ext_interrupt.h"
#include "STM32F103C_Drivers/HAL_Drivers/LCD_DRIVER/lcd.h"
#include "USART_DRIVER/usart.h"

void clock_init()

{

	//Enable clock GPIOA
	RCC_GPIOA_CLK_EN();
	//Enable clock GPIOB
	RCC_GPIOB_CLK_EN();
	RCC_AFIO_CLK_EN();
}

uint16_t recived_data ;

int main(void)
{
	clock_init();

	UART_Config_t UART ;
	UART.BaudRate = UART_BaudRate_115200 ;
	UART.FlowCTRL = UART_FLOWCTRL_NONE ;
	UART.IRQ_ENABLE = UART_IRQ_ENABLE_NONE ;
	UART.USART_MODE = UART_MODE_RX_TX ;
	UART.Parity = UART_PARITY_NONE ;
	UART.Payload_length = UART_PayloadLength_8B ;
	UART.StopBits = UART_StopBit_1 ;
	UART.P_IRQ_CALLBACK = NULL ;

	MCAL_UART_INIT(USART1, &UART);
	MCAL_UART_GPIO_SET_PINS(USART1);


	while(1)
	{


		MCAL_UART_RECEIVE_DATA(USART1, &recived_data, ENABLE);
		MCAL_UART_SEND_DATA(USART1, &recived_data, ENABLE);

	}



	return 0;
}



