/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "GPIO_DRIVER/gpio.h"
#include "EXTI_DRIVER/ext_interrupt.h"

#define TaskA_stack_sz 100
#define TaskB_stack_sz 100

#define OS_SET_PSP(add)			__asm volatile("mov r0, %0 \n\t msr PSP, r0 \n\t" : : "r" (add))
#define OS_SWITCH_SP_TO_PSP		__asm volatile(" mrs r0, CONTROL \n\t mov r1, #0x02 \n\t orr r0, r0, r1 \n\t msr CONTROL, r0 \n\t")
#define OS_SWITCH_SP_TO_MSP		__asm volatile(" mrs r0, CONTROL \n\t mov r1, #0x05 \n\t and r0, r0, r1 \n\t msr CONTROL, r0 \n\t")
#define OS_GENERATE_EXCEPTION 	__asm volatile("SVC #0x3")

extern int _estack;

//MAIN STACK
unsigned int _S_MSP = &_estack;
unsigned int _E_MSP;

//PROCESS STACK TASKA
unsigned int _S_PSP_TA;
unsigned int _E_PSP_TA;

//PROCESS STACK TASKB
unsigned int _S_PSP_TB;
unsigned int _E_PSP_TB;

uint8_t TaskA_flag, TaskB_flag, Flag = 0;

enum privilege_level {unprivileged, privileged};
void CPU_Access_Level(enum privilege_level lvl)
{
	switch(lvl)
	{
	case unprivileged:
		__asm("mrs r3, CONTROL \n\t"
				"orr r3, r3, #0x1 \n\t"
				"msr CONTROL,r3");
		break;
	case privileged:
		__asm("mrs r3, CONTROL \n\t"
				"lsr r3, r3, #0x1 \n\t"
				"lsl r3, r3, #0x1 \n\t"
				"msr CONTROL,r3");
		break;
	}
}

void clock_init()

{

	//Enable clock GPIOA
	//RCC_GPIOA_CLK_EN();
	//Enable clock GPIOB
	RCC_GPIOB_CLK_EN();
	RCC_AFIO_CLK_EN();

}


void SVC_Handler()
{
	CPU_Access_Level(privileged);
}

void HardFault_Handler()
{

}

void wait (int x)
{
	unsigned int i , j ;
	for (i= 0 ; i<x ; i++)
		for (j= 0 ; j<255 ; j++);
}


void EXTI9_CALLBACK(void)
{
	if (Flag == 0)
	{
		TaskA_flag =1;
		Flag = 1;
	}
	else if (Flag == 1)
	{
		TaskB_flag =1;
		Flag = 0;
	}

}

int TaskA (int a, int b, int c)
{
	return a+b+c;
}

int TaskB (int a, int b,int c, int d)
{
	return a+b+c+d;
}
void MainOs()
{
	_E_MSP = (_S_MSP - 512);

	_S_PSP_TA = (_E_MSP - 8);
	_E_PSP_TA = (_S_PSP_TA - TaskA_stack_sz);

	_S_PSP_TB = (_E_PSP_TA - 8);
	_E_PSP_TB = (_S_PSP_TB - TaskB_stack_sz);

	while(1)
	{
		__asm("nop \n\t");
		if (TaskA_flag == 1)
		{
			//Set PSP register to _S_PSP_TA
			OS_SET_PSP(_S_PSP_TA);

			//SP -> PSP
			OS_SWITCH_SP_TO_PSP;

			//Switch from privileged to unprivileged
			CPU_Access_Level(unprivileged);
			TaskA_flag =TaskA(1,2,3);

			//Switch from unprivileged to privileged
			OS_GENERATE_EXCEPTION;
			//SP -> MSP
			OS_SWITCH_SP_TO_MSP;
		}
		if (TaskB_flag == 1)
		{
			//Set PSP register to _S_PSP_TB
			OS_SET_PSP(_S_PSP_TB);

			//SP -> PSP
			OS_SWITCH_SP_TO_PSP;

			//Switch from privileged to unprivileged
			CPU_Access_Level(unprivileged);
			TaskB_flag =TaskB(1,2,3,4);

			//Switch from unprivileged to privileged
			OS_GENERATE_EXCEPTION;
			//SP -> MSP
			OS_SWITCH_SP_TO_MSP;
		}
	}
}

int main(void)
{

	clock_init();


	//Set EXTI Configuration
	EXTI_PIN_CONFIG_t EXTIConfig;
	EXTIConfig.EXTI_PIN = EXTI9PB9;
	EXTIConfig.TRIGGER_CASE = EXTI_TRIGGER_RISING;
	EXTIConfig.P_IRQ_CALLBACK = EXTI9_CALLBACK;
	EXTIConfig.IRQ_EN = EXTI_IRQ_ENABLE;
	MCAL_EXTI_Init(&EXTIConfig);


	//CPU_Access_Level(unprivileged);

	MainOs();
	while (1)
	{
		if(Flag)
		{
			Flag = 0;
		}
	}


}

