/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "GPIO_DRIVER/gpio.h"
#include "EXTI_DRIVER/ext_interrupt.h"

void clock_init()

{

	//Enable clock GPIOA
	//RCC_GPIOA_CLK_EN();
	//Enable clock GPIOB
	RCC_GPIOB_CLK_EN();
	RCC_AFIO_CLK_EN();

}



uint8_t Flag = 0;

void wait (int x)
{
	unsigned int i , j ;
	for (i= 0 ; i<x ; i++)
		for (j= 0 ; j<255 ; j++);
}

void EXTI9_CALLBACK(void)
{
	Flag = 1;
	wait(1000);
}

int main(void)
{

	clock_init();
	//Set EXTI Configuration
	EXTI_PIN_CONFIG_t EXTIConfig;
	EXTIConfig.EXTI_PIN = EXTI9PB9;
	EXTIConfig.TRIGGER_CASE = EXTI_TRIGGER_RISING;
	EXTIConfig.P_IRQ_CALLBACK = EXTI9_CALLBACK;
	EXTIConfig.IRQ_EN = EXTI_IRQ_ENABLE;
	MCAL_EXTI_Init(&EXTIConfig);

	GPIO_PIN_CONFIG_t PINCnfg;
	PINCnfg.GPIO_PIN_NO = GPIO_PIN13;
	PINCnfg.GPIO_MODE = GPIO_MODE_OUTPUT_PP;
	PINCnfg.GPIO_OUTPUT_SPEED= GPIO_SPEED_10MHZ;
	MCAL_GPIO_Init(GPIOB, &PINCnfg);

	Flag = 1;


	while (1)
	{
		if(Flag)
		{
			MCAL_GPIO_TOGGLE_PIN(GPIOB,GPIO_PIN13);
			Flag = 0;
		}
	}


}

