/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "STM32F103C_Drivers/MCAL_Drivers/GPIO_DRIVER/gpio.h"
#include "STM32F103C_Drivers/MCAL_Drivers/EXTI_DRIVER/ext_interrupt.h"
#include "STM32F103C_Drivers/HAL_Drivers/LCD_DRIVER/lcd.h"

uint8_t IRQ_Flag = 0;

void clock_init()

{

	//Enable clock GPIOA
	RCC_GPIOA_CLK_EN();
	//Enable clock GPIOB
	RCC_GPIOB_CLK_EN();
	RCC_AFIO_CLK_EN();
}

void EXTI1_Interrupt(void);

int main(void)
{
	clock_init();
	LCD_INIT();

	//MCAL_GPIO_SET_PIN_OUTPUT(GPIOA, GPIO_PIN13,GPIO_MODE_OUTPUT_PP,GPIO_SPEED_10MHZ);
    //CNF13=00: General purpose output push-pull, MODE13=01: Output mode, max speed 10 MHz


	MCAL_EXTI_SET( EXTI13PA13,  EXTI_TRIGGER_RISING ,EXTI_IRQ_ENABLE ,EXTI1_Interrupt );


	LCD_WRITE_STRING_POS("Waiting", LCD_BEGIN_AT_FIRST_ROW, 1);
	//MCAL_GPIO_WRITE_PIN(GPIOA, GPIO_PIN13,GPIO_PIN_SET); //set pin

	while (1)
	{
		if(IRQ_Flag)
		{
			LCD_clear_screen();
			LCD_WRITE_STRING_POS("EXTI0PB0", LCD_BEGIN_AT_FIRST_ROW, 1);
			for (int i = 0; i < 500000; i++); // arbitrary delay
			IRQ_Flag=0;
		}
	}


	return 0;
}


void EXTI1_Interrupt(void)
{
	IRQ_Flag=1;

	for (int i = 0; i < 5000; i++); // arbitrary delay

}
